### ISSUE TITLE
[DGSM] Disabling "Fixed" settings 'causes Dupes to only roll with 1 positive trait

### ISSUE THREAD

**Issue by Undeadbanana** [O-n-y/oxy.mods#114]
Interests are unaffected and can still roll between 1-3 and I'm unsure if Negative traits are affected, they only roll 1 which is what I think is correct.

The issue: Base game allows you to roll 1-2 positive traits per dupe. When this mod is enabled but the "Fixed Positive Traits" is disabled, the dupes will always roll 1 positive trait.

These are my settings: https://i.imgur.com/9fSJuwn.png

(I realize I could just add 2 fixed positive traits, since that's what I was rerolling for. Was just trying to play with few changes to dupe generation and came upon the bug.)

**Comment by O-n-y** [comment]
i could not reproduce the situation when base game generate more than 1 positive / negative trait (for colony start).
maybe some other of your mods do this ?

tested on release branch of the game U48-568201, DLC enabled.

**Comment by Undeadbanana** [comment]
I tested the mod solo, but I think I may have been on the experimental branch that was going to be released at the time (can't remember exactly if I was on that branch at this point) but I haven't played in a while so I'm sorry I can't be of more use.

**Comment by Undeadbanana** [comment]
I've been planning on hopping back in, if I can reproduce this issue I'll reopen it later but I'll close for now.

**Comment by maforget** [comment]
I have the same problem, with both option disabled, whatever the number of reroll I do all the traits always give 1 positive and 1 negative. It never gives more than that. 

Starting a new game seems to also only give 1 positive and 1 negative traits (not certain if it's supposed to be like that, because it does the same without mods). By loading a saved game is the only place where you can have more than 1 of each (printing pod), but again upon a reroll it always return only 1 postiive and 1 negative (when on the printing pod). 

The only way to have more than 1 is to set a fixed number of traits.
