### ISSUE TITLE
[DGSM] 3.6.7.37 Changing traits does not affect interest attribute points.

### ISSUE THREAD

**Issue by Gratiskatze24** [O-n-y/oxy.mods#167]
OS: Windows 11
Game Version: U51-600112-V
Mod Version: 3.6.7.37

Other installed mods: Mod Manager & Debug Console.

When changing positive or negative traits on any dupe, their interest attribute points do not change.

How to reproduce:

1. Make sure the "Count in generated by Positive / Negative trait points" options are turned on in the mod config.
2. Start a new survival game on Terra with the default settings.
3. Pick any dupe and change their traits. No matter what combination of positive and negative traits you pick, the interest attribute points do not change. 

The only way the change the interest attribute points is through rolling a new dupe (like in vanilla).

![image](https://github.com/user-attachments/assets/f7021718-01f9-424e-bba4-145f4d57274a)

**Comment by O-n-y** [comment]
I checked the issue you have, this was mad for a reason as temporary solution.

the reason is:

where there are multiple interests, the bonus from negative traits is randomly distributed from it with those, so when we change the negative trait - we would not know where to dustribute those best.

yes, when you only have 1 interest this is not a case, but i wanted to have this have same behavior, this is why it is made like this for now, till i wont find better solution.

**Comment by O-n-y** [comment]
this was so long time ago i forgot about all this :)

**Comment by O-n-y** [comment]
i could make it to be redistributed randomly again, but not sure if this is a desire solution

**Comment by O-n-y** [comment]
as DGSM was made to remove randomness

**Comment by O-n-y** [comment]
i will add the option to redistribute after trait change in settings, will push to beta soon for testing, announcement will be in Discord
