### ISSUE TITLE
Mod Manager window too tall on 4K resolution, 150% UI Scale @ModManager v2.9.3.179

### ISSUE THREAD

**Issue by Session10** [O-n-y/oxy.mods#18]
The Mod Manager window goes off the top and bottom of the screen if the UI is scaled up.

I'm playing at 3840x2160 resolution, UI scaled to 150%, fullscreen.

![20200711161545_1](https://user-images.githubusercontent.com/68166394/87233395-fdde4580-c394-11ea-9eb7-501f24206b22.jpg)

**Comment by O-n-y** [comment]
please provide information about your screen resolution, ui scale,  window/full screen etc, so i can test and check this out

**Comment by O-n-y** [comment]
Mod Manager updated to 2.9.4.200 release version:
+ Adjustment for dynamic height of Mods window, to respect scaling ratio (if you have UI scale set not to 100%)

**Comment by Yarbrough08** [comment]
I'm still having this issue with 2.9.4.200 (verified on the dll). I'm not sure if I should open a new one or not so I'll post here.
My monitor is 4k native and my desktop resolution is set to 2160p.
For me, it affects all game resolutions above 1080p. Every resolution above 1920x1080 it seems to stretch vertically more. 

1920x1080
![1080p](https://user-images.githubusercontent.com/16028072/87268222-8214f380-c48f-11ea-84cf-bdcef0ff7afd.jpg)

2400x1350
![1350p](https://user-images.githubusercontent.com/16028072/87268249-8ccf8880-c48f-11ea-9c7b-084bf01e0fd6.jpg)

2880x1620
![1620p](https://user-images.githubusercontent.com/16028072/87268263-92c56980-c48f-11ea-96ac-d4642840e4e7.jpg)

etc..

Other resolutions that I tested included 1800p and 2160p. I also tested 1440p but that's a slightly different aspect ratio than 0.5625. Pretty much anything above 2560x1440 renders the menu useless since you can't read or click on the buttons. On a positive note, changing the UI scale slider from 120% to 100% didnt seem to change anything for me -  so that problem seems to have been eliminated.

**Comment by O-n-y** [comment]
So, it is not related to scale, but only to resolution (i.e. with 100% scale - all same)? 
I currently do not have 4k monitor on the hand, but i will try to research this more. 
Now it sounds like it is not about scale (which i thought it would be), but about how 4K monitors render in particular.

**Comment by O-n-y** [comment]
Mod Manager updated to  2.9.5.203 release version:
+ Fix for a bug, introduced in previous (2.9.4.200) version
+ Adjustment for dynamic height of Mods window, to respect scaling ratio (if you have UI scale set not to 100%)

please let me know if you still have this issue on   2.9.5.203

**Comment by Yarbrough08** [comment]
I updated to 2.9.5.203 and do still have the issue.

Also, I was wrong about no effect from changing ui scale. At 1620p I changed the ui scale from 120% to 100% and got this difference that I noticed:

1620p 120%
![1620p 120%](https://user-images.githubusercontent.com/16028072/87332447-30a54c80-c501-11ea-9af2-ea5cb0e0567a.jpg)

1620p 100%
![1620p 100%](https://user-images.githubusercontent.com/16028072/87332499-431f8600-c501-11ea-9673-c1f32e0eea06.jpg)

I had checked the ui scale at 4k with no apparent change other than width, but I had not checked other resolutions with lower ui scale. 1440p at 100% scale seems normal:
![1440p](https://user-images.githubusercontent.com/16028072/87333843-5af80980-c503-11ea-9fbb-9d8a2c3d4004.jpg)

I will be happy to test more for you to get the issue resolved.

**Comment by O-n-y** [comment]
Please pm me in discord

**Comment by O-n-y** [comment]
Mod Manager updated to  2.9.6.221 release version:
+ Adjustment for dynamic height of Mods window, to respect scaling ratio (if you have UI scale set not to 100%) (i borrowed 4k monitor for short period of time, so now all should be fine :yum: )

**Comment by Yarbrough08** [comment]
The issue is resolved for me 😎

4k @ 120% scale
![20200713155423_1](https://user-images.githubusercontent.com/16028072/87352729-2d21bd80-c521-11ea-94f6-5dc056405179.jpg)
